# Generated by Django 2.0.6 on 2018-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
